# Generated by Django 3.0.3 on 2020-02-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_mechanic', '0002_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Imię')),
                ('surname', models.CharField(max_length=255, verbose_name='Nazwisko')),
                ('default_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_mechanic.Position')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_mechanic.Workshop')),
            ],
        ),
    ]
