# Generated by Django 3.0.3 on 2020-03-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_mechanic', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Nieprzydzielone'), (2, 'W toku'), (3, 'Zakończone')], default=1, verbose_name='Status'),
        ),
    ]
